name: Node CI

on:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        env:
          PRIVATE_KEY: ${{ secrets.buildPem }}
        run: |
          cd chrome
          npm install yarn crx
          yarn
          npm run bumpVersion
          npm run build
          cd ..
          cat <<< $PRIVATE_KEY > ../build.pem
          npx crx pack chrome/release -p ../build.pem -o BaiduExporter.crx
      - name: Set git identity
        run : |
          git config --global user.email "tofuliang@gmail.com"
          git config --global user.name "tofuliang"
          git add BaiduExporter.crx chrome/updates.xml chrome/manifest.json
          git checkout *
          git commit -m "update crx"
          git push
